home:
    path: /
    controller: App\Controller\SegmentController::listSegments

detail:
    path: /segment/{id}
    controller: App\Controller\SegmentController::editSegment

create:
    path: /segment/
    controller: App\Controller\SegmentController::createSegment